### ISSUE TITLE
Feature: User can see related books

### ISSUE THREAD

**Issue by rachel-lyy** [rachel-lyy/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Based on the user's book search, they will be give four results. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on one of the search results and learn more about the book.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Code search results based on wireframes
- [ ] Book title, author and cover art should be displayed 
- [ ] Each book should be linked to Book Details page
