### ISSUE TITLE
Feature: User can view book information and select it for their reading goals

### ISSUE THREAD

**Issue by rachel-lyy** [rachel-lyy/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to click on a book, view book information then select it for their reading goals.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will see information about the book they have selected, read book details like summary, author, amount of pages. They will also see related books. The user can save the book which will apply the reading goal parameters (chunking and read by date).

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Code book details page based on wire frame
- [ ] Apply API data on to the page: book title(s), author(s), cover art, book summary, etc.
- [ ] Allow user to save book, return to search page, or choose one of the related books.
