### ISSUE TITLE
Feature: User can view a reading goal dashboard

### ISSUE THREAD

**Issue by rachel-lyy** [rachel-lyy/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view their reading goal dashboards and see the reading miles stones based on the information provided in the reading questionnaire. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to view their reading goal dashboards and see the reading miles stones based on the information provided in the reading questionnaire. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Code dashboard based on wireframe
- [ ] Do calculation based on reading goal date and chunking method
- [ ] Display timeline of when user should complete reading milestones with page/chapter amounts
