### ISSUE TITLE
Feature: User can save reading goals to their Google Calendar

### ISSUE THREAD

**Issue by rachel-lyy** [rachel-lyy/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to save reading goals, from the dashboard, to their Google Calendar. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click on a calendar icon next to their reading goal and add it to their Google Calendar. 

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Configure Google Calendar API on app
- [ ] Add functionality to dashboard for user to add event to their Google Calendar
- [ ] Pass reading goal data to Google Calendar API
- [ ] Test on personal calendar
